version: '3.9'

services:
    postgres: 
      image: postgres:14
      ports:
        - 5432:5432
      environment:
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_USER: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_PASSWORD}
        POSTGRES_HOST: ${POSTGRES_PASSWORD}
        POSTGRES_PORT: ${POSTGRES_PORT}
      volumes: 
        - ./tmp/pgdata:/var/lib/postgresql/data