version: '3.9'

services:
    postgres: 
      image: postgres:14
      ports:
        - 5432:5432
      environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres
        POSTGRES_DB: postgres
        POSTGRES_HOST: postgres
        POSTGRES_PORT: 5432
      volumes: 
        - ./tmp/pgdata:/var/lib/postgresql/data